### ISSUE TITLE
chrono CVE-2020-26235

### ISSUE THREAD

**Issue by jxs** [prisma/tiberius#190]
Hi! Currently, tiberius depends on `chrono`  which seems to have a security issue that isn't fixed for a long while already: [CVE-2020-26235](https://rustsec.org/advisories/RUSTSEC-2020-0159)
Which is raised in the bug tracker as well (see also the last comments there): chronotope/chrono#499

on `refinery` I changed the dependency to `time` directly.
Thanks!

**Comment by pimeys** [comment]
Oh god.

This is going to be a massive effort in Prisma. I'm pushing it forward now but I can't give you a proper timeline when I can do any work on Tiberius.

We should maybe have it additionally next to chrono first with a feature flag, then make it the default feature in the next preview release.

**Comment by jxs** [comment]
>This is going to be a massive effort in Prisma. I'm pushing it forward now but I can't give you a proper timeline when I can do any work on Tiberius.

no, of course, I got that feeling when searching in the issue tracker if this was already reported and saw multiple `chrono` related issues. 

>We should maybe have it additionally next to chrono first with a feature flag, then make it the default feature in the next major release.

yeah makes sense, I would follow the same approach.  
Thanks for your interest!

**Comment by pimeys** [comment]
It's probably not too hard to do. I isolated all chrono functionality to here: https://github.com/prisma/tiberius/blob/main/src/tds/time/chrono.rs

Otherwise the crate should be playing with the date and time formats returned from TDS. If you want to give it a try, I'd add a new module next to the `chrono.rs` and try to implement the conversions there. I'd love to do this too, but the issue tracker is having everything else in front of this until we can prioritize again and allocate some time for a dev to take a look.

The Tiberius part might be easy, triggering the change in all our org a bit more work.

**Comment by pimeys** [comment]
@jxs there's a PR now open to support time crate. Do you want to check it out and test it? Merging to main soonish, cutting a new version when one other PR gets merged.

**Comment by jxs** [comment]
Hi @pimeys how are you? Seems I came too late sorry. Thanks for addressing this!
