### ISSUE TITLE
Problem with blob (type=Image) query

### ISSUE THREAD

**Issue by wackydoo** [prisma/tiberius#56]
It is fantastic to see new progress in tiberius.  I had tried to use a much earlier version but no support of blob types was a show stopper.  

I have tried using the sample code from the documentation, both against the tokio and the async-std executors.  My database is Microsoft SQL Server 2016 (SP2-CU8) (KB4505830) - 13.0.5426.0 (X64) .

A simple SELECT query worked fine with both executors, however when I tried another query  which retrieved a single row with two columns, row  index (integer key column) and corresponding BLOB (Image type), from another table the result is corrupted:

```
let mut stream = client.simple_query(_query2).await?;
assert!(stream.next_resultset());
println!("{:?}",stream.columns().unwrap());
```
returns the name of the index and BLOB column

```
[Column { name: "i", column_type: Int4 }, Column { name: "琀攀猀琀搀愀琀愀开戀氀漀戀", column_type: Image }]
```

The types are correct for both columns but the column name for the BLOB column should be 'b'.  It is corrupted.  Also if I continue on and try extract the rows I get a "Error: Protocol error: invalid token type 0".  

I am not overriding the default tiberius features and get the same results with the latest stable rust on both Windows and Ubuntu 64bit.    Any suggestions for how to debug this?

I tried running the same query with freetds "tsql" and it returned the correct data.

**Comment by pimeys** [comment]
I think we have something broken in the TDS column parsing, especially for the image type, which is not that well documented due to it being kind of deprecated and me didn't really figure out more details after I got it working. Of course we need to support that type, and here we have some extra info in the token data I didn't expect when I programmed support for `image`.

I have a dinner coming, so I can give you some pointers now to debug this, and if you're unlucky finding the problem (and throwing a PR back to us), I'll take a look on Monday!

First please take a look into [token_col_metadata.rs](https://github.com/prisma/tiberius/blob/master/src/tds/codec/token/token_col_metadata.rs#L141) how we decode the column info. You see how we start by decoding the column type info first, after which we see the name of the column.

If we jump a [few lines down](https://github.com/prisma/tiberius/blob/master/src/tds/codec/token/token_col_metadata.rs#L183) we find the spot where I might've made a mistake. We [have a test](https://github.com/prisma/tiberius/blob/master/tests/query.rs#L883-L919) for image, and I also [added a test](https://github.com/prisma/tiberius/commit/b9596807dafa9f7c2ddb60daa6b4e0a8c60e79bc) for the column name, which seems to pass.

So I missed something, and I expected that (coming from the "used SQL Server 15 years ago the last time" position).

Thank you for the report. Hopefully this works for you before Monday, if not, I'll fix it.

P.S. For debugging, wherever you have `src` coming in as `SqlReadBytes`, you can call the [`debug_buffer`](https://github.com/prisma/tiberius/blob/master/src/client/connection.rs#L434-L437) method, which outputs a beautiful hex dump to your terminal (I used that on many long evenings when something was wrong in my TDS implementation). I believe we do not read something that is in the wire in your case, or we read too much info, and of course the column name is garbage due to us reading a UCS-2 string from the wrong position...

**Comment by wackydoo** [comment]
Thanks for your suggestions.  I am not great at debugging rust so I haven't worked out how to use debug_buffer to output the hex dump, however I was able to capture the TDS in wireshark so I am going through the TDS spec from Trying to make sense of the Type 4 Response containing data.  (I can see the correct column names in the hexdump.) I'll summarize and get back.

**Comment by pimeys** [comment]
I'm interested of your schema. There must be something we're not parsing. How is it different compared to the test schema I linked in the comment above?

-------- Original Message --------

**Comment by pimeys** [comment]
You could try to modify the test in Tiberius I linked to model the difference in your schema and see if you can get it to break. This would help me to debug the problem better.

And to use the `debug_stub`, you need to call the method in a position where a bug might be happening. Here we see the data in the wire right after we've read the column type. The cursor is in the position where we expect a `u8`, followed by a length and a UCS-2 string defining the table name. To see this position:

```diff
diff --git a/src/tds/codec/token/token_col_metadata.rs b/src/tds/codec/token/token_col_metadata.rs
index df15ae3..3b00a93 100644
--- a/src/tds/codec/token/token_col_metadata.rs
+++ b/src/tds/codec/token/token_col_metadata.rs
@@ -181,6 +181,7 @@ impl BaseMetaDataColumn {
                 read_varchar(src, len as usize).await?;
             }
             TypeInfo::VarLenSized(VarLenType::Image, _, _) => {
+                src.debug_buffer();
                 src.read_u8().await?;

                 // table name
```
Then point to the local copy of Tiberius in your `Cargo.toml`:
```toml
tiberius = { path = "/path/to/tiberius" }
```
Run the code that breaks and try to make it panic, and you should see a hex dump.

The other points of interest for debugs would be:
```diff
diff --git a/src/tds/codec/token/token_col_metadata.rs b/src/tds/codec/token/token_col_metadata.rs
index df15ae3..d94cec2 100644
--- a/src/tds/codec/token/token_col_metadata.rs
+++ b/src/tds/codec/token/token_col_metadata.rs
@@ -138,6 +138,7 @@ impl TokenColMetaData {

             // read all metadata for each column
             for _ in 0..column_count {
+                src.debug_buffer();
                 let base = BaseMetaDataColumn::decode(src).await?;
                 let col_name_len = src.read_u8().await?;
```
And from there forward. Just go line by line and see where we read too many or too little bytes. I'm 99% sure some of these lines are buggy here, but it's hard to proof without knowing the actual schema.

**Comment by pimeys** [comment]
Ok, so I'm reading the tedious library source code, and found one thing that we might be doing wrong in Tiberius. The `IMAGE`/`NTEXT` and `TEXT` types have a table name in their metadata, which we've been reading and which has been working at least in the test cases. But. In some cases the table name can be in multiple parts, and this is the mysterious `u8` that comes before the table name length and the name data. So, in this patch we read the u8, and then loop through reading the different parts of the table name until done.

Could you please try [this branch](https://github.com/prisma/tiberius/tree/table-name-fix) and see if it fixes the problem for you?

There are some mystery things I do for `TEXT` as you can see from a few lines above. There are three `u16` values before the length and name and using the code from the `NTEXT` and `IMAGE` types doesn't work here. I suspect there might be another bug lurking in that part.

**Comment by wackydoo** [comment]
I have confirmed that the table-name-fix retrieves the correct table names.  (I haven't checked that actual row data yet.) 

In case it is useful, I'll add some more information from wireshark

My query is from a single table

```
SELECT testdata_blob.blob_id as blob_id, testdata_blob.blob_blob as blob0000 FROM dbo.testdata_blob testdata_blob (nolock) WHERE testdata_blob.blob_id = 139726950";
```
where the blob_id column is Int4 and the blob_blob data, aliased as blob0000, is Image.

When I send the query the head of the response payload looks like

```
00000000: 8102 0000 0000 0010 0038 0762 006c 006f  .........8.b.l.o
00000010: 0062 005f 0069 0064 0000 0000 0009 0022  .b._.i.d......."
00000020: ffff ff7f 0203 0064 0062 006f 000d 0074  .......d.b.o...t
00000030: 0065 0073 0074 0064 0061 0074 0061 005f  .e.s.t.d.a.t.a._
00000040: 0062 006c 006f 0062 0008 6200 6c00 6f00  .b.l.o.b..b.l.o.
00000050: 6200 3000 3000 3000 3000 d166 1054 0810  b.0.0.0.0..f.T..
00000060: 6475 6d6d 7920 7465 7874 7074 7200 0000  dummy textptr...
00000070: 6475 6d6d 7954 5300 bb56 0000 789c b5bd  dummyTS..V..x...
00000080: d98e 6447 9225 f84e 80ff 108f 3580 97b5  ..dG.%.N....5...
00000090: 2e22 baf8 1b2b 9b5d 4d20 99c9 2199 358f  ."...+.]M ..!.5.
```
I can see column names "blob_id" and "blob000" in there, but as you have found the table name "dbo.testdata" is also there!

**Comment by pimeys** [comment]
Yeah, so it's in two parts! That was easier than I expected, whew :)

Do you have any use for this table name property, should it be public? It's only for the deprecated types and I don't really know where I'd use this information, so what Tiberius does it reads it and forgets it immediately...

**Comment by pimeys** [comment]
The data also contains a pointer and a timestamp as you can see from the wireshark output. In my tests these have always been `dummy textptr` and `dummyTS`, and I don't know could there be a case where we'd have something else in these. So what we do is we read the pointer and timestamp, but just free them immediately without storing the values anywhere.

**Comment by pimeys** [comment]
Please check the row data and then write a comment to my PR, so I can merge it and cut a new release.

**Comment by wackydoo** [comment]
> Please check the row data and then write a comment to my PR, so I can merge it and cut a new release.

Commented on PR.  All is OK.  Thanks for the quick resolution.

**Comment by pimeys** [comment]
Thank you for testing and reporting. It's very valuable until we actually start using this in Prisma!

**Comment by pimeys** [comment]
Merged to master, releasing a new patch release now.
